import { defineCcnaModules } from "@/content/cisco/ccna/types";

export const ccnaModules = defineCcnaModules([
  {
    id: "foundations", slug: "network-foundations", order: 1,
    title: "Network Foundations", shortTitle: "Foundations",
    description: "Build the packet, device, architecture, media, transport, and virtualization models that every later configuration depends on.",
    outcome: "Explain how traffic moves through a modern small or enterprise network and identify the correct component, medium, and protocol for the job.",
    domains: ["1.0 Network Fundamentals"],
    sourceChapters: ["Volume 1 · Chapters 1–3", "Volume 2 · Chapters 13–15"],
  },
  {
    id: "ios", slug: "cisco-ios", order: 2,
    title: "Cisco IOS Operations", shortTitle: "Cisco IOS",
    description: "Operate the CLI deliberately: move through modes, save state, address interfaces, and secure management access.",
    outcome: "Make a small IOS change, prove the running state, preserve it, and recover from a common access mistake.",
    domains: ["1.0 Network Fundamentals", "2.0 Network Access", "4.0 IP Services", "5.0 Security Fundamentals"],
    sourceChapters: ["Volume 1 · Chapters 4, 6, and 15"],
  },
  {
    id: "switching", slug: "ethernet-switching", order: 3,
    title: "Ethernet and Switching", shortTitle: "Switching",
    description: "Read frames, predict MAC-table decisions, validate switch interfaces, discover neighbors, and bundle links with LACP.",
    outcome: "Predict and verify how a switch handles each frame before reaching for configuration changes.",
    domains: ["1.0 Network Fundamentals", "2.0 Network Access"],
    sourceChapters: ["Volume 1 · Chapters 2, 5, 7, and 10", "Volume 2 · Chapter 9"],
  },
  {
    id: "campus", slug: "vlans-campus", order: 4,
    title: "VLANs and Campus Networks", shortTitle: "VLANs + Campus",
    description: "Create broadcast boundaries, carry them across trunks, route between them, and keep Layer 2 paths loop-free.",
    outcome: "Build and troubleshoot a small switched campus with access, voice, trunk, inter-VLAN, and Rapid PVST+ behavior.",
    domains: ["2.0 Network Access"],
    sourceChapters: ["Volume 1 · Chapters 8–10 and 17"],
  },
  {
    id: "addressing", slug: "ip-addressing", order: 5,
    title: "IPv4 and IPv6 Addressing", shortTitle: "IP Addressing",
    description: "Turn prefixes into usable address plans, distinguish address scopes, and verify host and router parameters without guesswork.",
    outcome: "Subnet IPv4, plan IPv6 prefixes, configure both protocol families, and prove the resulting host and router state.",
    domains: ["1.0 Network Fundamentals"],
    sourceChapters: ["Volume 1 · Chapters 11–14 and 22–25", "Volume 2 · Chapter 7"],
  },
  {
    id: "routing", slug: "routing", order: 6,
    title: "Routing and IP Connectivity", shortTitle: "Routing",
    description: "Interpret route evidence, predict forwarding, build resilient static paths, and operate single-area OSPFv2.",
    outcome: "Explain exactly why a router selected a path, configure the intended alternative, and verify neighbor and forwarding state.",
    domains: ["3.0 IP Connectivity"],
    sourceChapters: ["Volume 1 · Chapters 16–21 and 25"],
  },
  {
    id: "services", slug: "ip-services", order: 7,
    title: "IP Services", shortTitle: "IP Services",
    description: "Operate the supporting services that make addressing, names, time, telemetry, translation, and file movement useful.",
    outcome: "Configure or explain every CCNA service, then verify the service from both the network device and client path.",
    domains: ["4.0 IP Services"],
    sourceChapters: ["Volume 2 · Chapters 7 and 9–12"],
  },
  {
    id: "security", slug: "security", order: 8,
    title: "Security Fundamentals", shortTitle: "Security",
    description: "Connect threats to controls, protect device access, filter traffic, and harden the access layer against common local attacks.",
    outcome: "Apply a least-privilege control, prove it allows the intended flow, and diagnose the evidence when it blocks the wrong one.",
    domains: ["5.0 Security Fundamentals"],
    sourceChapters: ["Volume 2 · Chapters 2–8"],
  },
  {
    id: "wireless", slug: "wireless", order: 9,
    title: "Wireless Networking", shortTitle: "Wireless",
    description: "Connect RF behavior to Cisco architectures, infrastructure links, WLAN settings, and modern wireless security.",
    outcome: "Interpret a controller-based WLAN design and configure a secure WPA2 PSK client path in the GUI.",
    domains: ["1.0 Network Fundamentals", "2.0 Network Access", "5.0 Security Fundamentals"],
    sourceChapters: ["Volume 1 · Chapters 26–29"],
  },
  {
    id: "automation", slug: "automation", order: 10,
    title: "Automation and Programmability", shortTitle: "Automation",
    description: "Read controller, API, JSON, AI/ML, and infrastructure-as-code concepts as one operational system rather than isolated buzzwords.",
    outcome: "Trace an automated intent from a northbound request through a controller to device state, then interpret the returned JSON evidence.",
    domains: ["6.0 Automation and Programmability"],
    sourceChapters: ["Volume 2 · Chapters 16–19", "Official v1.1 objectives · AI/ML and Terraform updates"],
  },
  {
    id: "troubleshooting", slug: "troubleshooting", order: 11,
    title: "Troubleshooting Workflows", shortTitle: "Troubleshooting",
    description: "Turn symptoms into bounded failure domains across physical, switching, routing, service, security, and wireless layers.",
    outcome: "Use a repeatable evidence ladder to isolate one fault, fix the smallest cause, and document proof of recovery.",
    domains: ["Cross-domain verification"],
    sourceChapters: ["Volume 1 · Chapters 7, 18, and 21", "Volume 2 · Chapters 2, 8, and 10"],
  },
  {
    id: "review", slug: "final-review", order: 12,
    title: "Final Review and Exam Readiness", shortTitle: "Final Review",
    description: "Close objective gaps with mixed-domain retrieval, configuration interpretation, and a final capstone fault set.",
    outcome: "Demonstrate complete v1.1 objective coverage and choose the next study action from evidence rather than confidence alone.",
    domains: ["All six exam domains"],
    sourceChapters: ["Volume 2 · Chapter 20", "Official Cisco 200-301 v1.1 exam topics"],
  },
]);

export const ccnaModuleById = new Map(ccnaModules.map((moduleEntry) => [moduleEntry.id, moduleEntry]));
