import { defineCcnaObjectives, type CcnaObjective } from "@/content/cisco/ccna/types";

type ObjectiveInput = Omit<CcnaObjective, "domain" | "domainNumber" | "weight">;

const domains = {
  1: { domain: "Network Fundamentals", weight: 20 },
  2: { domain: "Network Access", weight: 20 },
  3: { domain: "IP Connectivity", weight: 25 },
  4: { domain: "IP Services", weight: 10 },
  5: { domain: "Security Fundamentals", weight: 15 },
  6: { domain: "Automation and Programmability", weight: 10 },
} as const;

function objective(domainNumber: keyof typeof domains, input: ObjectiveInput): CcnaObjective {
  return { ...input, domainNumber, ...domains[domainNumber] };
}

export const ccnaObjectives = defineCcnaObjectives([
  objective(1, { id: "1.1.a", verb: "explain", title: "Role and function of routers" }),
  objective(1, { id: "1.1.b", verb: "explain", title: "Role and function of Layer 2 and Layer 3 switches" }),
  objective(1, { id: "1.1.c", verb: "explain", title: "Role and function of next-generation firewalls and IPS" }),
  objective(1, { id: "1.1.d", verb: "explain", title: "Role and function of access points" }),
  objective(1, { id: "1.1.e", verb: "explain", title: "Role and function of controllers" }),
  objective(1, { id: "1.1.f", verb: "explain", title: "Role and function of endpoints" }),
  objective(1, { id: "1.1.g", verb: "explain", title: "Role and function of servers" }),
  objective(1, { id: "1.1.h", verb: "explain", title: "Role and function of Power over Ethernet" }),
  objective(1, { id: "1.2.a", verb: "describe", title: "Two-tier network architecture" }),
  objective(1, { id: "1.2.b", verb: "describe", title: "Three-tier network architecture" }),
  objective(1, { id: "1.2.c", verb: "describe", title: "Spine-leaf network architecture" }),
  objective(1, { id: "1.2.d", verb: "describe", title: "WAN architecture" }),
  objective(1, { id: "1.2.e", verb: "describe", title: "Small office and home office architecture" }),
  objective(1, { id: "1.2.f", verb: "describe", title: "On-premises and cloud architecture" }),
  objective(1, { id: "1.3.a", verb: "compare", title: "Single-mode fiber, multimode fiber, and copper" }),
  objective(1, { id: "1.3.b", verb: "compare", title: "Shared-media and point-to-point connections" }),
  objective(1, { id: "1.4", verb: "explain", title: "Interface and cable issues: collisions, errors, duplex, and speed" }),
  objective(1, { id: "1.5", verb: "compare", title: "TCP and UDP" }),
  objective(1, { id: "1.6", verb: "configure", title: "IPv4 addressing and subnetting" }),
  objective(1, { id: "1.7", verb: "describe", title: "Private IPv4 addressing" }),
  objective(1, { id: "1.8", verb: "configure", title: "IPv6 addressing and prefixes" }),
  objective(1, { id: "1.9.a", verb: "describe", title: "IPv6 global unicast, unique local, and link-local addresses" }),
  objective(1, { id: "1.9.b", verb: "describe", title: "IPv6 anycast addresses" }),
  objective(1, { id: "1.9.c", verb: "describe", title: "IPv6 multicast addresses" }),
  objective(1, { id: "1.9.d", verb: "describe", title: "Modified EUI-64 interface identifiers" }),
  objective(1, { id: "1.10", verb: "verify", title: "IP parameters on Windows, macOS, and Linux clients" }),
  objective(1, { id: "1.11.a", verb: "describe", title: "Nonoverlapping Wi-Fi channels" }),
  objective(1, { id: "1.11.b", verb: "describe", title: "SSID concepts" }),
  objective(1, { id: "1.11.c", verb: "describe", title: "RF concepts" }),
  objective(1, { id: "1.11.d", verb: "describe", title: "Wireless encryption" }),
  objective(1, { id: "1.12", verb: "explain", title: "Server virtualization, containers, and VRFs" }),
  objective(1, { id: "1.13.a", verb: "explain", title: "MAC address learning and aging" }),
  objective(1, { id: "1.13.b", verb: "explain", title: "Ethernet frame switching" }),
  objective(1, { id: "1.13.c", verb: "explain", title: "Frame flooding" }),
  objective(1, { id: "1.13.d", verb: "explain", title: "MAC address table behavior" }),

  objective(2, { id: "2.1.a", verb: "configure", title: "Access ports for data and voice VLANs" }),
  objective(2, { id: "2.1.b", verb: "configure", title: "Default VLAN behavior" }),
  objective(2, { id: "2.1.c", verb: "configure", title: "Inter-VLAN connectivity" }),
  objective(2, { id: "2.2.a", verb: "configure", title: "Interswitch trunk ports" }),
  objective(2, { id: "2.2.b", verb: "configure", title: "IEEE 802.1Q tagging" }),
  objective(2, { id: "2.2.c", verb: "configure", title: "Native VLAN behavior" }),
  objective(2, { id: "2.3", verb: "configure", title: "CDP and LLDP neighbor discovery" }),
  objective(2, { id: "2.4", verb: "configure", title: "Layer 2 and Layer 3 EtherChannel using LACP" }),
  objective(2, { id: "2.5.a", verb: "interpret", title: "Rapid PVST+ root bridge and port selection" }),
  objective(2, { id: "2.5.b", verb: "interpret", title: "Rapid PVST+ port roles and states" }),
  objective(2, { id: "2.5.c", verb: "interpret", title: "PortFast behavior" }),
  objective(2, { id: "2.5.d", verb: "interpret", title: "Root guard, loop guard, BPDU filter, and BPDU guard" }),
  objective(2, { id: "2.6", verb: "describe", title: "Cisco wireless architectures and AP modes" }),
  objective(2, { id: "2.7", verb: "describe", title: "Physical WLAN infrastructure connections" }),
  objective(2, { id: "2.8", verb: "describe", title: "Network device management access" }),
  objective(2, { id: "2.9", verb: "interpret", title: "Wireless LAN GUI configuration for client connectivity" }),

  objective(3, { id: "3.1.a", verb: "interpret", title: "Routing table protocol code" }),
  objective(3, { id: "3.1.b", verb: "interpret", title: "Routing table prefix" }),
  objective(3, { id: "3.1.c", verb: "interpret", title: "Routing table network mask" }),
  objective(3, { id: "3.1.d", verb: "interpret", title: "Routing table next hop" }),
  objective(3, { id: "3.1.e", verb: "interpret", title: "Routing table administrative distance" }),
  objective(3, { id: "3.1.f", verb: "interpret", title: "Routing table metric" }),
  objective(3, { id: "3.1.g", verb: "interpret", title: "Gateway of last resort" }),
  objective(3, { id: "3.2.a", verb: "explain", title: "Router forwarding with longest prefix match" }),
  objective(3, { id: "3.2.b", verb: "explain", title: "Router forwarding with administrative distance" }),
  objective(3, { id: "3.2.c", verb: "explain", title: "Router forwarding with routing protocol metric" }),
  objective(3, { id: "3.3.a", verb: "configure", title: "IPv4 and IPv6 default static routes" }),
  objective(3, { id: "3.3.b", verb: "configure", title: "IPv4 and IPv6 network static routes" }),
  objective(3, { id: "3.3.c", verb: "configure", title: "IPv4 and IPv6 host static routes" }),
  objective(3, { id: "3.3.d", verb: "configure", title: "Floating static routes" }),
  objective(3, { id: "3.4.a", verb: "configure", title: "Single-area OSPFv2 neighbor adjacencies" }),
  objective(3, { id: "3.4.b", verb: "configure", title: "Single-area OSPFv2 point-to-point networks" }),
  objective(3, { id: "3.4.c", verb: "configure", title: "Single-area OSPFv2 broadcast networks and DR/BDR selection" }),
  objective(3, { id: "3.4.d", verb: "configure", title: "Single-area OSPFv2 router ID" }),
  objective(3, { id: "3.5", verb: "describe", title: "First-hop redundancy protocols" }),

  objective(4, { id: "4.1", verb: "configure", title: "Inside source NAT using static mappings and pools" }),
  objective(4, { id: "4.2", verb: "configure", title: "NTP client and server modes" }),
  objective(4, { id: "4.3", verb: "explain", title: "DHCP and DNS roles" }),
  objective(4, { id: "4.4", verb: "explain", title: "SNMP in network operations" }),
  objective(4, { id: "4.5", verb: "describe", title: "Syslog facilities and severity levels" }),
  objective(4, { id: "4.6", verb: "configure", title: "DHCP client and relay" }),
  objective(4, { id: "4.7", verb: "explain", title: "QoS classification, marking, queuing, congestion, policing, and shaping" }),
  objective(4, { id: "4.8", verb: "configure", title: "SSH remote access" }),
  objective(4, { id: "4.9", verb: "describe", title: "TFTP and FTP capabilities" }),

  objective(5, { id: "5.1", verb: "describe", title: "Threats, vulnerabilities, exploits, and mitigation" }),
  objective(5, { id: "5.2", verb: "describe", title: "Security program awareness, training, and physical controls" }),
  objective(5, { id: "5.3", verb: "configure", title: "Device access using local passwords" }),
  objective(5, { id: "5.4", verb: "describe", title: "Password policy, MFA, certificates, and biometrics" }),
  objective(5, { id: "5.5", verb: "describe", title: "IPsec remote-access and site-to-site VPNs" }),
  objective(5, { id: "5.6", verb: "configure", title: "IPv4 access control lists" }),
  objective(5, { id: "5.7", verb: "configure", title: "Layer 2 security with DHCP snooping, DAI, and port security" }),
  objective(5, { id: "5.8", verb: "compare", title: "Authentication, authorization, and accounting" }),
  objective(5, { id: "5.9", verb: "describe", title: "WPA, WPA2, and WPA3 wireless security" }),
  objective(5, { id: "5.10", verb: "configure", title: "WPA2 PSK WLAN using the GUI" }),

  objective(6, { id: "6.1", verb: "explain", title: "Impact of automation on network management" }),
  objective(6, { id: "6.2", verb: "compare", title: "Traditional and controller-based networking" }),
  objective(6, { id: "6.3.a", verb: "describe", title: "Separation of control plane and data plane" }),
  objective(6, { id: "6.3.b", verb: "describe", title: "Northbound and southbound APIs" }),
  objective(6, { id: "6.4", verb: "explain", title: "Generative AI, predictive AI, and machine learning in network operations" }),
  objective(6, { id: "6.5", verb: "describe", title: "REST API authentication, CRUD, HTTP verbs, and data encoding" }),
  objective(6, { id: "6.6", verb: "recognize", title: "Capabilities of Ansible and Terraform" }),
  objective(6, { id: "6.7", verb: "interpret", title: "JSON-encoded data" }),
]);

export const ccnaObjectiveById = new Map(ccnaObjectives.map((item) => [item.id, item]));

export const ccnaDomains = Object.entries(domains).map(([number, value]) => ({
  number: Number(number),
  ...value,
  objectiveCount: ccnaObjectives.filter((item) => item.domainNumber === Number(number)).length,
}));
