import { defineLinuxCapabilities, defineLinuxModules } from "@/content/linux/network-engineering/types";

const MAN7 = "https://man7.org/linux/man-pages/dir_all_alphabetic.html";
const UBUNTU = "https://documentation.ubuntu.com/server/explanation/networking/";
const SYSTEMD = "https://www.freedesktop.org/software/systemd/man/latest/";
const IP = "https://man7.org/linux/man-pages/man8/ip.8.html";
const NETPLAN = "https://netplan.readthedocs.io/en/stable/";
const NFT = "https://wiki.nftables.org/wiki-nftables/index.php/Main_Page";
const OPENSSH = "https://www.openssh.com/manual.html";
const TCPDUMP = "https://www.tcpdump.org/manpages/tcpdump.1.html";
const WIREGUARD = "https://www.wireguard.com/quickstart/";
const FRR = "https://docs.frrouting.org/en/latest/";
const DOCKER = "https://docs.docker.com/engine/network/";
const KERNEL = "https://docs.kernel.org/networking/index.html";

export const linuxModules = defineLinuxModules([
  { id: "foundations", slug: "foundations", order: 1, title: "Linux Foundations for Network Work", shortTitle: "Foundations", description: "Understand the kernel, shell, files, permissions, packages, and processes without drifting into unrelated desktop administration.", outcome: "Work safely in a Linux terminal, locate configuration and evidence, and explain which layer owns a networking result.", capabilityGroup: "Host and shell fundamentals", sourceLinks: [{ label: "Linux man-pages project", href: MAN7, kind: "manual" }] },
  { id: "operations", slug: "system-operations", order: 2, title: "Services, Boot, Logs, and Remote Operations", shortTitle: "System Operations", description: "Operate systemd services, logs, SSH access, timers, and configuration changes as a repeatable network-support workflow.", outcome: "Change one service safely, prove active state, correlate its logs, and preserve a rollback path.", capabilityGroup: "Service operations", sourceLinks: [{ label: "systemd manual collection", href: SYSTEMD, kind: "official" }, { label: "OpenSSH manuals", href: OPENSSH, kind: "official" }] },
  { id: "interfaces", slug: "interfaces-addressing", order: 3, title: "Interfaces and IP Addressing", shortTitle: "Interfaces + IP", description: "Read and configure link state, IPv4, IPv6, neighbors, and persistent host networking across common Linux managers.", outcome: "Explain the active host network state and make a persistent addressing change without confusing runtime and configuration files.", capabilityGroup: "Link and address state", sourceLinks: [{ label: "ip(8) manual", href: IP, kind: "manual" }, { label: "Ubuntu networking documentation", href: UBUNTU, kind: "official" }, { label: "Netplan documentation", href: NETPLAN, kind: "official" }] },
  { id: "routing", slug: "routing-segmentation", order: 4, title: "Routing and Network Segmentation", shortTitle: "Routing + Segmentation", description: "Control forwarding with routes, policy rules, VLANs, bridges, bonds, VRFs, namespaces, and virtual Ethernet pairs.", outcome: "Predict the kernel route decision and build isolated or redundant Layer 2/Layer 3 paths with direct verification.", capabilityGroup: "Forwarding and isolation", sourceLinks: [{ label: "iproute2 manual collection", href: IP, kind: "manual" }, { label: "Linux kernel networking documentation", href: KERNEL, kind: "official" }] },
  { id: "transport", slug: "sockets-transport", order: 5, title: "Sockets, TCP, UDP, ICMP, and Performance", shortTitle: "Sockets + Transport", description: "Connect processes to listening sockets, transport states, MTU behavior, reachability tests, and measurable throughput.", outcome: "Trace a client flow from process and socket through TCP/UDP/IP evidence and separate latency, loss, MTU, and capacity symptoms.", capabilityGroup: "Transport evidence", sourceLinks: [{ label: "Linux man-pages project", href: MAN7, kind: "manual" }, { label: "Linux kernel networking documentation", href: KERNEL, kind: "official" }] },
  { id: "services", slug: "network-services", order: 6, title: "DNS, DHCP, Time, and Local Network Services", shortTitle: "Core Services", description: "Operate the client and server sides of name resolution, address leasing, time synchronization, and lightweight lab services.", outcome: "Prove whether a failure belongs to resolver policy, DNS, DHCP, time, routing, or the service process itself.", capabilityGroup: "Core infrastructure services", sourceLinks: [{ label: "Ubuntu Server networking documentation", href: UBUNTU, kind: "official" }, { label: "BIND 9 Administrator Reference", href: "https://bind9.readthedocs.io/en/latest/", kind: "official" }, { label: "chrony documentation", href: "https://chrony-project.org/documentation.html", kind: "official" }] },
  { id: "troubleshooting", slug: "troubleshooting-capture", order: 7, title: "Troubleshooting and Packet Capture", shortTitle: "Troubleshooting", description: "Use an evidence ladder across link, address, neighbor, route, socket, service, DNS, and packet layers.", outcome: "Capture the minimum useful evidence, localize a fault, and document a conclusion another engineer can reproduce.", capabilityGroup: "Diagnosis and packet evidence", sourceLinks: [{ label: "tcpdump manual", href: TCPDUMP, kind: "official" }, { label: "Wireshark display-filter reference", href: "https://www.wireshark.org/docs/dfref/", kind: "official" }] },
  { id: "firewall", slug: "firewall-nat-qos", order: 8, title: "Firewalling, NAT, Connection Tracking, and QoS", shortTitle: "Firewall + NAT", description: "Read the Netfilter packet path, build nftables policy, translate traffic, and control queues without locking yourself out.", outcome: "Implement a least-privilege stateful rule set, verify translations and counters, and recover safely from policy mistakes.", capabilityGroup: "Host enforcement and traffic control", sourceLinks: [{ label: "nftables wiki", href: NFT, kind: "official" }, { label: "tc(8) manual", href: "https://man7.org/linux/man-pages/man8/tc.8.html", kind: "manual" }] },
  { id: "tunnels", slug: "secure-access-tunnels", order: 9, title: "Secure Access, Tunnels, and VPNs", shortTitle: "Access + Tunnels", description: "Harden SSH, move traffic through controlled forwards, and build common Linux underlay and overlay tunnels.", outcome: "Choose the correct tunnel, verify its control and data planes, and explain the encryption and routing boundaries.", capabilityGroup: "Remote access and encapsulation", sourceLinks: [{ label: "OpenSSH manuals", href: OPENSSH, kind: "official" }, { label: "WireGuard quick start", href: WIREGUARD, kind: "official" }, { label: "strongSwan documentation", href: "https://docs.strongswan.org/docs/latest/", kind: "official" }] },
  { id: "routing-services", slug: "routing-network-daemons", order: 10, title: "Linux Routers and Network Daemons", shortTitle: "Routers + Daemons", description: "Turn a Linux host into a controlled router and operate dynamic routing, load balancing, discovery, telemetry, and forwarding services.", outcome: "Run Linux as a lab router or network service node with explicit forwarding, routing-daemon, listener, policy, and telemetry evidence.", capabilityGroup: "Network appliance roles", sourceLinks: [{ label: "FRRouting documentation", href: FRR, kind: "official" }, { label: "Linux kernel networking documentation", href: KERNEL, kind: "official" }] },
  { id: "virtual-automation", slug: "virtual-networks-automation", order: 11, title: "Virtual Networks and Automation", shortTitle: "Virtual + Automation", description: "Connect container and hypervisor networking to namespaces, bridges, NAT, JSON output, shell automation, Python, Ansible, and Git.", outcome: "Build a reproducible virtual network and collect or change state with reviewable automation rather than fragile one-off commands.", capabilityGroup: "Reproducible network operations", sourceLinks: [{ label: "Docker networking overview", href: DOCKER, kind: "official" }, { label: "Ansible network guides", href: "https://docs.ansible.com/ansible/latest/network/", kind: "official" }] },
  { id: "reliability", slug: "observability-security-capstone", order: 12, title: "Observability, Hardening, and Incident Practice", shortTitle: "Reliability + Capstone", description: "Monitor host networking, understand eBPF visibility, harden the management plane, and solve realistic cross-layer incidents.", outcome: "Operate a hardened Linux network node, explain its telemetry, and complete an end-to-end incident and capstone acceptance test.", capabilityGroup: "Operational readiness", sourceLinks: [{ label: "Linux BPF documentation", href: "https://docs.kernel.org/bpf/", kind: "official" }, { label: "Prometheus node exporter", href: "https://github.com/prometheus/node_exporter", kind: "official" }, { label: "Ubuntu security documentation", href: "https://documentation.ubuntu.com/security/", kind: "official" }] },
]);

export const linuxModuleById = new Map(linuxModules.map((moduleEntry) => [moduleEntry.id, moduleEntry]));

const capabilityTitles: Record<string, string[]> = {
  foundations: ["Explain the Linux network operating model", "Navigate files and configuration safely", "Transform text with shell pipelines", "Manage users, permissions, and sudo", "Inspect packages, processes, and resources"],
  operations: ["Operate systemd services and dependencies", "Query journald and traditional logs", "Use and troubleshoot OpenSSH", "Schedule repeatable tasks with timers and cron", "Make reversible configuration changes"],
  interfaces: ["Trace the Linux packet path and Netlink state", "Inspect link state and driver evidence", "Configure and verify IPv4 addressing", "Configure and verify IPv6 addressing", "Interpret ARP and IPv6 neighbor state", "Persist networking with Netplan, NetworkManager, or networkd"],
  routing: ["Interpret kernel routes and route lookup", "Use policy routing and multiple tables", "Build VLAN interfaces and Linux bridges", "Build bonds and understand link aggregation", "Use VRFs for routing-table isolation", "Build namespaces and veth paths"],
  transport: ["Map sockets to processes", "Interpret TCP connection state", "Troubleshoot UDP and ICMP behavior", "Diagnose MTU and path-MTU failures", "Test applications with nc, curl, and OpenSSL", "Measure capacity with iperf3 and interface counters"],
  services: ["Explain resolver order and NSS", "Troubleshoot DNS with dig and resolvectl", "Operate local DNS caching and authoritative service", "Troubleshoot DHCP clients and leases", "Provide DHCP and relay services in a lab", "Synchronize and verify time with chrony"],
  troubleshooting: ["Apply a layered Linux network triage workflow", "Use ping, tracepath, traceroute, and mtr", "Capture precise traffic with tcpdump", "Read TCP, DNS, DHCP, ARP, and ICMP packets", "Use tshark and reusable pcap workflows", "Diagnose link counters, offloads, and driver state"],
  firewall: ["Explain Netfilter hooks and connection tracking", "Build nftables tables, chains, rules, and sets", "Implement stateful host firewall policy", "Configure and verify SNAT, DNAT, and masquerade", "Operate UFW and firewalld without losing the underlying model", "Shape and classify traffic with tc"],
  tunnels: ["Harden SSH management access", "Use SSH local, remote, dynamic, and jump-host forwarding", "Build GRE, IP-in-IP, and SIT tunnels", "Build and troubleshoot WireGuard", "Understand Linux IPsec and XFRM", "Build VXLAN overlays and recognize MACsec boundaries"],
  "routing-services": ["Enable safe IPv4 and IPv6 forwarding", "Operate OSPF with FRRouting", "Operate BGP with FRRouting", "Provide reverse proxy and load-balancing service", "Collect LLDP, SNMP, and syslog evidence", "Validate lightweight network services and listeners"],
  "virtual-automation": ["Explain container network namespaces and bridges", "Operate Docker bridge, host, none, and custom networks", "Build libvirt bridge and tap connectivity", "Write safe shell network checks", "Consume JSON state with jq", "Use Python, Ansible, and Git for network changes"],
  reliability: ["Monitor host network health and capacity", "Explain eBPF network visibility and limits", "Harden a Linux network node", "Investigate an unexpected listener", "Resolve a DNS and time incident", "Resolve asymmetric routing and NAT", "Complete the Linux network operations capstone"],
};

export const linuxCapabilities = defineLinuxCapabilities(linuxModules.flatMap((moduleEntry) =>
  (capabilityTitles[moduleEntry.id] ?? []).map((title, index) => ({
    id: `LIN-${moduleEntry.order}.${index + 1}`,
    moduleId: moduleEntry.id,
    title,
  })),
));

export const linuxCapabilityById = new Map(linuxCapabilities.map((capability) => [capability.id, capability]));
